name: Build and Deploy to ECS via ECR

on:
  push:
    branches: [ main ]
permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code
env:
  ECR_REPOSITORY: dev1
  ECS_CLUSTER: nginx-cluster
  ECS_SERVICE: nginx-service
  CONTAINER_NAME: nginx
  TASK_DEFINITION: nginx-task
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Static code analysis with Trivy
    - name: Run Trivy static code analysis
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "config"
        format: "table"
        exit-code: "0"
        severity: "CRITICAL,HIGH"
        ignore-unfixed: true

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Scan Docker image for vulnerabilities
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "fs"
        format: "table"
        exit-code: "0"
        severity: "CRITICAL,HIGH"
        ignore-unfixed: true

    # Build Docker image
    - name: Build Docker image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    # Scan Docker image for vulnerabilities
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: "image"
        image-ref: ${{ env.IMAGE_URI }}
        format: "table"
        exit-code: "0"
        severity: "CRITICAL,HIGH"
        ignore-unfixed: true

    # Push Docker image to Amazon ECR
    - name: Push image to Amazon ECR
      id: push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Update ECS task definition with new image
    - name: Download current task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION }} \
          --query taskDefinition > task-definition.json

    # Update task definition with new ECR image
    - name: Update task definition with new ECR image
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        jq --arg IMAGE_URI "${IMAGE_URI}" \
          '.containerDefinitions[0].image = $IMAGE_URI | 
           del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .deregisteredAt)' \
          task-definition.json > register-task-definition.json

    # Register new task definition
    - name: Register new task definition
      id: register-task
      run: |
        NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://register-task-definition.json --query 'taskDefinition.taskDefinitionArn' --output text)
        echo "NEW_TASK_DEFINITION=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

    # Update ECS service with new task definition
    - name: Update ECS service
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --task-definition ${{ env.NEW_TASK_DEFINITION }} \
          --force-new-deployment